import dotenv from "dotenv"
dotenv.config({})
import { Request, Response, NextFunction } from "express";
import axios from "axios";


interface LogEntry {
    ip: string | undefined,
    method: string,
    url: string,
    status: number,
    duration: number,
    user_agent: string | undefined,
    user_id: string | undefined,
    project_id: string,
    alert?: string,
    severity?: "low" | "medium" | "high",
    timestamp: string,
}

export function logsential(config: { apiKey: string, projectId: string }) {
    return (req: Request, res: Response, next: NextFunction) => {
        const start = Date.now();

        res.on("finish", async () => {
            const log: LogEntry = {
                ip: req.ip,
                method: req.method,
                url: req.originalUrl,
                status: res.statusCode,
                duration: Date.now() - start,
                user_agent: req.headers["user-agent"],
                user_id: (req as any).user?.id || undefined,  // optional JWT tracking later
                project_id: config.projectId,
                timestamp: new Date().toISOString(),
            };

            //             id bigint generated by default as identity primary key,
            //   project_id uuid references projects(id) on delete cascade,   -- IMPORTANT
            //   user_id uuid references auth.users(id),                      -- optional
            //   ip text,
            //   method text,
            //   url text,
            //   status integer,
            //   duration integer,
            //   user_agent text,
            //   alert text,
            //   severity text,
            //   timestamp timestamptz default now()

            try {
                await axios.post("http://localhost:4000/collect", log, {
                    headers: { "x-api-key": config.apiKey }
                })

            } catch (error) {
                console.error("Collector API error: ", error)
            }

            // const { error } = await supabase.from("logs").insert([log]);
            // if (error) console.error("Supabase error: ", error)
            console.log('[LOG]', log)
        })

        next()
    }
}

module.exports = { logsential }